# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes

# Build settings
plugins:
  - jekyll-feed

include: 
  - _pages/
  - _assets/

keep_files:
  - assets

exclude:
  - node_modules/
  - package-lock.json
  - package.json
  - webpack.mix.js
  - yarn.lock
  - readme.md
  - safelist.txt
  - tailwind.config.js
  - yarn-error.log

# incremental: false
# detach: false
# port: 4000
# host: 127.0.0.1
# baseurl: /
# show_dir_listing: false
# permalink: date
# paginate_path: '/page:num'
# timezone: null
# quiet: false
# verbose: false

#Defaults
defaults:
  js: _assets/scripts/app.js
  css: _assets/css/main.css
  svg: _assets/icons/

# Liquid Config
liquid:
  error_mode: warn
rdiscount:
  extensions: []
redcarpet:
  extensions: []

# Markdown Config
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  show_warnings: false